policy_names: ["unitree"]
policy_merge_steps: 50

mujoco:
  robot_name: "h12"
  scene_name: "27dof"
  experiment_name: "h12_locomotion"

  render_dt: 0.02
  episode_length: 5
  simulation_dt: 0.001

  enable_GUI: True
  fix_base: False
  real_time: False
  log_data: False
  elastic_band: False

real:
  channel_id: 1
  net_interface: eth0
  use_mujoco: True
